version: '2'
services:

    sys-activities-website:
        build: 
            context: ./images/webserver
        environment:
            PYTHONUNBUFFERED: 'true'
        container_name: sys-activities-api
        depends_on:
            - sys-activities-datacontainer
        volumes_from: 
            - sys-activities-datacontainer
        ports:
            - '8050:8000'
            
    sys-activities-redis:
        image: 'redis:3.0-alpine'
        command: redis-server  --appendonly yes --requirepass devpassword 
        container_name: sys-activities-redis
        depends_on:
            - sys-activities-datacontainer
        volumes_from: 
            - sys-activities-datacontainer
        ports:
            - '6379:6379'

    sys-activities-orientdb:
        image: 'orientdb'
        command: /orientdb/bin/server.sh  -Ddistributed=true
        container_name: sys-activities-orientdb
        environment:
                ORIENTDB_ROOT_PASSWORD: 'fenris'
                ORIENTDB_NODE_NAME: 'node1'
        depends_on:
            - sys-activities-datacontainer
        volumes_from: 
            - sys-activities-datacontainer
        ports:
            - '2424:2424' 
            - '2480:2480' 

    sys-activities-datacontainer:
        image: busybox
        container_name: sys-activities-datacontainer
        volumes:
            - src/app:/app            
            - datavolume/redis/data:/data
            - datavolume/orientdb/config:/orientdb/config
            - datavolume/orientdb/databases:/orientdb/databases 
            - datavolume/orientdb/backup:/orientdb/backup 